usePackage <- function(p) {
    if (!is.element(p, installed.packages()[,1]))
        install.packages(p, dep = TRUE)
    require(p, character.only = TRUE)
}

useGitPackage <- function(p, link) {
    if (!is.element(p, installed.packages()[,1]))
        install_github(link)
    require(p, character.only = TRUE)
}

usePackage("magicaxis")
usePackage("MASS")
usePackage("rgl")
usePackage("devtools")
usePackage("shinyRGL")
useGitPackage("LaplacesDemon", "Statisticat/LaplacesDemon")
useGitPackage("hyper.fit", "asgr/hyper.fit")

data(TFR)
data(MJB)
data(GAMAsmVsize)

algsTable = list(
    "optim" = list(
        "Nelder-Mead"= list("name" = "Nelder and Mead (1965)",
                            "link" = "",
                            "alg"  = "Nelder-Mead",
                            "Specs"= list()),
        "BFGS"       = list("name" = "Broyden, Fletcher, Goldfarb and Shanno (1970)",
                            "link" = "",
                            "alg"  = "BFGS",
                            "Specs"= list()),
        "CG"         = list("name" = "Fletcher and Reeves + options (1964)",
                            "link" = "",
                            "alg"  = "CG",
                            "Specs"= list()),
        "L-BFGS-B"   = list("name" = "Byrd et. al. (1995)",
                            "link" = "",
                            "alg"  = "L-BFGS-B",
                            "Specs"= list()),
        "SANN"       = list("name" = "Belisle (1992)",
                            "link" = "",
                            "alg"  = "SANN",
                            "Specs"= list()),
        "Brent"      = list("name" = "info, one-dimensional",
                            "link" = "",
                            "alg"  = "Brent",
                            "Specs"= list())
    ),
    "LA" = list(
        "AGA"        = list("name" = "Adaptive Gradient Ascent",
                            "link" = "",
                            "alg"  = "AGA",
                            "Specs"= list()),
        "BFGS"       = list("name" = "Broyden-Fletcher-Goldfarb-Shanno",
                            "link" = "",
                            "alg"  = "BFGS",
                            "Specs"= list()),
        "BHHH"       = list("name" = "Berndt et al.",
                            "link" = "",
                            "alg"  = "BHHH",
                            "Specs"= list()),
        "CG"         = list("name" = "Conjugate Gradient",
                            "link" = "",
                            "alg"  = "CG",
                            "Specs"= list()),
        "DFP"        = list("name" = "Davidon-Fletcher-Powell",
                            "link" = "",
                            "alg"  = "DFP",
                            "Specs"= list()),
        "HAR"        = list("name" = "Adaptive Hit-And-Run",
                            "link" = "",
                            "alg"  = "HAR",
                            "Specs"= list()),
        "HJ"         = list("name" = "Hooke-Jeeves",
                            "link" = "",
                            "alg"  = "HJ",
                            "Specs"= list()),
        "LBFGS"      = list("name" = "Limited-memory BFGS",
                            "link" = "",
                            "alg"  = "LBFGS",
                            "Specs"= list()),
        "LM"         = list("name" = "Levenberg-Marquardt",
                            "link" = "",
                            "alg"  = "LM",
                            "Specs"= list()),
        "NM"         = list("name" = "Nelder-Mead",
                            "link" = "",
                            "alg"  = "NM",
                            "Specs"= list()),
        "NR"         = list("name" = "Newton-Raphson",
                            "link" = "",
                            "alg"  = "NR",
                            "Specs"= list()),
        "PSO"        = list("name" = "Particle Swarm Optimization",
                            "link" = "",
                            "alg"  = "PSO",
                            "Specs"= list()),
        "Rprop"      = list("name" = "Resilient Backpropagation",
                            "link" = "",
                            "alg"  = "Rprop",
                            "Specs"= list()),
        "SGD"        = list("name" = "Stochastic Gradient Descent",
                            "link" = "",
                            "alg"  = "SGD",
                            "Specs"= list()),
        "SOMA"       = list("name" = "Self-Organizing Migration Algorithm",
                            "link" = "",
                            "alg"  = "SOMA",
                            "Specs"= list()),
        "SPG"        = list("name" = "Spectral Projected Gradient",
                            "link" = "",
                            "alg"  = "SPG",
                            "Specs"= list()),
        "SR1"        = list("name" = "Symmetric Rank-One",
                            "link" = "",
                            "alg"  = "SR1",
                            "Specs"= list()),
        "TR"         = list("name" = "Trust Region",
                            "link" = "",
                            "alg"  = "TR",
                            "Specs"= list())
        ),
    "LD" = list(
        "ADMG"       = list("name" = "Adaptive Directional Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcadmg",
                            "alg"  = "ADMG",
                            "Specs"= list()),
        "AGG"        = list("name" = "Adaptive Griddy-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcagg",
                            "alg"  = "AGG",
                            "Specs"= list()),
        "AHMC"       = list("name" = "Adaptive Hamiltonian Monte Carlo",
                            "link" = "http://www.bayesian-inference.com/mcmcahmc",
                            "alg"  = "AHMC",
                            "Specs"= list()),
        "AM"         = list("name" = "Adaptive Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcam",
                            "alg"  = "AM",
                            "Specs"= list()),
        "AMWG"       = list("name" = "Adaptive Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcamwg",
                            "alg"  = "AMWG",
                            "Specs"= list()),
        "AMM"        = list("name" = "Adaptive-Mixture Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcamm",
                            "alg"  = "AMM",
                            "Specs"= list()),
        "AIES"       = list("name" = "Affine-Invariant Ensemble Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcaies",
                            "alg"  = "AIES",
                            "Specs"= list()),
        "CHARM"      = list("name" = "Componentwise Hit-And-Run Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmccharm",
                            "alg"  = "CHARM",
                            "Specs"= list()),
        "DRAM"       = list("name" = "Delayed Rejection Adaptive Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcdram",
                            "alg"  = "DRAM",
                            "Specs"= list()),
        "DRM"        = list("name" = "Delayed Rejection Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcdrm",
                            "alg"  = "DRM",
                            "Specs"= list()),
        "DEMC"       = list("name" = "Differential Evolution Markov Chain",
                            "link" = "http://www.bayesian-inference.com/mcmcdemc",
                            "alg"  = "DEMC",
                            "Specs"= list()),
        "ESS"        = list("name" = "Elliptical Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcess",
                            "alg"  = "ESS",
                            "Specs"= list()),
        "Gibbs"      = list("name" = "Gibbs Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcgibbs",
                            "alg"  = "Gibbs",
                            "Specs"= list()),
        "GG"         = list("name" = "Griddy-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcgg",
                            "alg"  = "GG",
                            "Specs"= list()),
        "HMC"        = list("name" = "Hamiltonian Monte Carlo",
                            "link" = "http://www.bayesian-inference.com/mcmchmc",
                            "alg"  = "HMC",
                            "Specs"= list()),
        "HMCDA"      = list("name" = "Hamiltonian Monte Carlo with Dual-Averaging",
                            "link" = "http://www.bayesian-inference.com/mcmchmc",
                            "alg"  = "HMCDA",
                            "Specs"= list()),
        "HARM"       = list("name" = "Hit-And-Run Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcharm",
                            "alg"  = "HARM",
                            "Specs"= list()),
        "IM"         = list("name" = "Independence Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcim",
                            "alg"  = "IM",
                            "Specs"= list()),
        "INCA"       = list("name" = "Interchain Adaptation",
                            "link" = "http://www.bayesian-inference.com/mcmcinca",
                            "alg"  = "INCA",
                            "Specs"= list()),
        "MALA"       = list("name" = "Metropolis-Adjusted Langevin Algorithm",
                            "link" = "http://www.bayesian-inference.com/mcmcmala",
                            "alg"  = "MALA",
                            "Specs"= list()),
        "MCMCMC"     = list("name" = "Metropolis-Coupled Markov Chain Monte Carlo",
                            "link" = "http://www.bayesian-inference.com/mcmcmcmcmc",
                            "alg"  = "MCMCMC",
                            "Specs"= list()),
        "MWG"        = list("name" = "Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcmwg",
                            "alg"  = "MWG",
                            "Specs"= list()),
        "MTM"        = list("name" = "Multiple-Try Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcmtm",
                            "alg"  = "MTM",
                            "Specs"= list()),
        "NUTS"       = list("name" = "No-U-Turn Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcnuts",
                            "alg"  = "NUTS",
                            "Specs"= list()),
        "OHSS"       = list("name" = "Oblique Hyperrectangle Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcohss",
                            "alg"  = "OHSS",
                            "Specs"= list()),
        "pCN"        = list("name" = "Preconditioned Crank-Nicolson",
                            "link" = "http://www.bayesian-inference.com/mcmcpcn",
                            "alg"  = "pCN",
                            "Specs"= list()),
        "RDMH"       = list("name" = "Random Dive Metropolis-Hastings",
                            "link" = "http://www.bayesian-inference.com/mcmcrdmh",
                            "alg"  = "RDMH",
                            "Specs"= list()),
        "RWM"        = list("name" = "Random-Walk Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcrwm",
                            "alg"  = "RWM",
                            "Specs"= list()),
        "RSS"        = list("name" = "Reflective Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcrss",
                            "alg"  = "RSS",
                            "Specs"= list()),
        "Refractive" = list("name" = "Refractive Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcrefractive",
                            "alg"  = "Refractive",
                            "Specs"= list()),
        "RJ"         = list("name" = "Reversible-Jump",
                            "link" = "http://www.bayesian-inference.com/mcmcrj",
                            "alg"  = "RJ",
                            "Specs"= list()),
        "RAM"        = list("name" = "Robust Adaptive Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcram",
                            "alg"  = "RAM",
                            "Specs"= list()),
        "SAMWG"      = list("name" = "Sequential Adaptive Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcsamwg",
                            "alg"  = "SAMWG",
                            "Specs"= list()),
        "SMWG"       = list("name" = "Sequential Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcsmwg",
                            "alg"  = "SMWG",
                            "Specs"= list()),
        "Slice"      = list("name" = "Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcslice",
                            "alg"  = "Slice",
                            "Specs"= list()),
        "SGLD"       = list("name" = "Stochastic Gradient Langevin Dynamics",
                            "link" = "http://www.bayesian-inference.com/mcmcsgld",
                            "alg"  = "SGLD",
                            "Specs"= list()),
        "THMC"       = list("name" = "Tempered Hamiltonian Monte Carlo",
                            "link" = "http://www.bayesian-inference.com/mcmcthmc",
                            "alg"  = "THMC",
                            "Specs"= list()),
        "twalk"      = list("name" = "t-walk",
                            "link" = "http://www.bayesian-inference.com/mcmctwalk",
                            "alg"  = "twalk",
                            "Specs"= list()),
        "UESS"       = list("name" = "Univariate Eigenvector Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcuess",
                            "alg"  = "UESS",
                            "Specs"= list()),
        "USAMWG"     = list("name" = "Updating Sequential Adaptive Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcusamwg",
                            "alg"  = "USAMWG",
                            "Specs"= list()),
        "USMWG"      = list("name" = "Updating Sequential Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcusmwg",
                            "alg"  = "USMWG",
                            "Specs"= list())
        )
    )