library("magicaxis")
library("MASS")
library("rgl")
library("devtools")
library("shinyRGL")
library("mcmcplots")
library("LaplacesDemon")
library("hyper.fit")

data(hogg)
data(FP6dFGS)
data(TFR)
data(MJB)
data(GAMAsmVsize)

algsTable = list(
    "optim" = list(
        "Nelder-Mead"= list("name" = "Nelder and Mead",
                            "link" = "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optim.html?Brent",
                            "alg"  = "Nelder-Mead",
                            "Specs"= list("Grid"=list("spec"="Grid","default"="seq(-0.1,0.1, len=5)"))),
        "BFGS"       = list("name" = "Broyden, Fletcher, Goldfarb and Shanno",
                            "link" = "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optim.html?Brent",
                            "alg"  = "BFGS",
                            "Specs"= list()),
        "CG"         = list("name" = "Conjugate Gradients",
                            "link" = "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optim.html?Brent",
                            "alg"  = "CG",
                            "Specs"= list()),
        "L-BFGS-B"   = list("name" = "Byrd et. al.",
                            "link" = "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optim.html?Brent",
                            "alg"  = "L-BFGS-B",
                            "Specs"= list()),
        "SANN"       = list("name" = "Simulated Annealing",
                            "link" = "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optim.html?Brent",
                            "alg"  = "SANN",
                            "Specs"= list())
#         "Brent"      = list("name" = "info, one-dimensional",
#                             "link" = "https://stat.ethz.ch/R-manual/R-devel/library/stats/html/optim.html?Brent",
#                             "alg"  = "Brent",
#                             "Specs"= list())
    ),
    "LA" = list(
        "AGA"        = list("name" = "Adaptive Gradient Ascent",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "AGA",
                            "Specs"= list()),
        "BFGS"       = list("name" = "Broyden-Fletcher-Goldfarb-Shanno",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "BFGS",
                            "Specs"= list()),
#         "BHHH"       = list("name" = "Berndt et al.",
#                             "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
#                             "alg"  = "BHHH",
#                             "Specs"= list()),
        "CG"         = list("name" = "Conjugate Gradient",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "CG",
                            "Specs"= list()),
        "DFP"        = list("name" = "Davidon-Fletcher-Powell",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "DFP",
                            "Specs"= list()),
        "HAR"        = list("name" = "Adaptive Hit-And-Run",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "HAR",
                            "Specs"= list()),
        # might work
#         "HJ"         = list("name" = "Hooke-Jeeves",
#                             "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
#                             "alg"  = "HJ",
#                             "Specs"= list()),
        "LBFGS"      = list("name" = "Limited-memory BFGS",
                            "link" = "",
                            "alg"  = "LBFGS",
                            "Specs"= list()),
        "LM"         = list("name" = "Levenberg-Marquardt",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "LM",
                            "Specs"= list()),
        "NM"         = list("name" = "Nelder-Mead",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "NM",
                            "Specs"= list()),
        "NR"         = list("name" = "Newton-Raphson",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "NR",
                            "Specs"= list()),
        "PSO"        = list("name" = "Particle Swarm Optimization",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "PSO",
                            "Specs"= list()),
        "Rprop"      = list("name" = "Resilient Backpropagation",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "Rprop",
                            "Specs"= list()),
#         "SGD"        = list("name" = "Stochastic Gradient Descent",
#                             "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
#                             "alg"  = "SGD",
#                             "Specs"= list()),
        "SOMA"       = list("name" = "Self-Organizing Migration Algorithm",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "SOMA",
                            "Specs"= list()),
        "SPG"        = list("name" = "Spectral Projected Gradient",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "SPG",
                            "Specs"= list()),
        "SR1"        = list("name" = "Symmetric Rank-One",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "SR1",
                            "Specs"= list()),
        "TR"         = list("name" = "Trust Region",
                            "link" = "http://www.bayesian-inference.com/softwaredoc/LaplaceApproximation",
                            "alg"  = "TR",
                            "Specs"= list())
        ),
    "LD" = list(
        "ADMG"       = list("name" = "Adaptive Directional Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcadmg",
                            "alg"  = "ADMG",
                            "Specs"= list("n"=list("spec"="n","default"="0"),
                                          "Periodicity"=list("spec"="Periodicity","default"="50"))),
        "AGG"        = list("name" = "Adaptive Griddy-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcagg",
                            "alg"  = "AGG",
                            "Specs"= list("Grid"=list("spec"="Grid","default"="GaussHermiteQuadRule(3)$nodes"),
                                          "dparm"=list("spec"="dparm","default"="NULL"),
                                          "smax"=list("spec"="smax","default"="Inf"),
                                          "CPUs"=list("spec"="CPUs","default"="1"),
                                          "Packages"=list("spec"="Packages","default"="NULL"),
                                          "Dyn.libs"=list("spec"="Dyn.libs","default"="NULL"))),
        "AHMC"       = list("name" = "Adaptive Hamiltonian Monte Carlo",
                            "link" = "http://www.bayesian-inference.com/mcmcahmc",
                            "alg"  = "AHMC",
                            "Specs"= list("epsilon"=list("spec"="epsilon","default"="rep(0.02, 3)"), # can accept vector
                                          "L"=list("spec"="L","default"="2"),
                                          "Periodicity"=list("spec"="Periodicity","default"="10"))),
        "AM"         = list("name" = "Adaptive Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcam",
                            "alg"  = "AM",
                            "Specs"= list("Adaptive"=list("spec"="Adaptive","default"="500"),
                                          "Periodicity"=list("spec"="Periodicity","default"="10"))),
        "AMWG"       = list("name" = "Adaptive Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcamwg",
                            "alg"  = "AMWG",
                            "Specs"= list("Periodicity"=list("spec"="Periodicity","default"="50"))),
        "AMM"        = list("name" = "Adaptive-Mixture Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcamm",
                            "alg"  = "AMM",
                            "Specs"= list("Adaptive"=list("spec"="Adaptive","default"="500"),
                                          "B"=list("spec"="B","default"="NULL"),
                                          "n"=list("spec"="n","default"="0"),
                                          "Periodicity"=list("spec"="Periodicity","default"="10"),
                                          "w"=list("spec"="w","default"="0.05"))),
        "AIES"       = list("name" = "Affine-Invariant Ensemble Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcaies",
                            "alg"  = "AIES",
                            "Specs"= list("Nc"=list("spec"="Nc","default"="6"),
                                          "Z"=list("spec"="Z","default"="NULL"),
                                          "beta"=list("spec"="beta","default"="2"),
                                          "CPUs"=list("spec"="CPUs","default"="1"),
                                          "Packages"=list("spec"="Packages","default"="NULL"),
                                          "Dyn.libs"=list("spec"="Dyn.libs","default"="NULL"))),
        "CHARM"      = list("name" = "Componentwise Hit-And-Run Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmccharm",
                            "alg"  = "CHARM",
                            "Specs"= list("alpha.star"=list("spec"="alpha.star","default"="0.44"))),
        "DRAM"       = list("name" = "Delayed Rejection Adaptive Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcdram",
                            "alg"  = "DRAM",
                            "Specs"= list("Adaptive"=list("spec"="Adaptive","default"="500"),
                                          "Periodicity"=list("spec"="Periodicity","default"="10"))),
        "DRM"        = list("name" = "Delayed Rejection Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcdrm",
                            "alg"  = "DRM",
                            "Specs"= list()),
        "DEMC"       = list("name" = "Differential Evolution Markov Chain",
                            "link" = "http://www.bayesian-inference.com/mcmcdemc",
                            "alg"  = "DEMC",
                            "Specs"= list("Nc"=list("spec"="Nc","default"="3"),
                                          "Z"=list("spec"="Z","default"="NULL"),
                                          "gamma"=list("spec"="gamma","default"="NULL"),
                                          "w"=list("spec"="w","default"="0.1"))),
        "ESS"        = list("name" = "Elliptical Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcess",
                            "alg"  = "ESS",
                            "Specs"= list("B"=list("spec"="B","default"="NULL"))),
        "GG"         = list("name" = "Griddy-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcgg",
                            "alg"  = "GG",
                            "Specs"= list("Grid"=list("spec"="Grid","default"="seq(from=-0.1,to=0.1,len=5)"),
                                          "dparm"=list("spec"="dparm","default"="NULL"),
                                          "CPUs"=list("spec"="CPUs","default"="1"),
                                          "Packages"=list("spec"="Packages","default"="NULL"),
                                          "Dyn.libs"=list("spec"="Dyn.libs","default"="NULL"))),
        "HMC"        = list("name" = "Hamiltonian Monte Carlo",
                            "link" = "http://www.bayesian-inference.com/mcmchmc",
                            "alg"  = "HMC",
                            "Specs"= list("epsilon"=list("spec"="epsilon","default"="rep(0.02, 3)"), # can accept vector
                                          "L"=list("spec"="L","default"="2"))),
        "HMCDA"      = list("name" = "Hamiltonian Monte Carlo with Dual-Averaging",
                            "link" = "http://www.bayesian-inference.com/mcmchmc",
                            "alg"  = "HMCDA",
                            "Specs"= list("A"=list("spec"="A","default"="500"),
                                          "delta"=list("spec"="delta","default"="0.65"),
                                          "epsilon"=list("spec"="epsilon","default"="NULL"), # scalar
                                          "Lmax"=list("spec"="Lmax","default"="1"),
                                          "lambda"=list("spec"="lambda","default"="0.1"))),
        "HARM"       = list("name" = "Hit-And-Run Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcharm",
                            "alg"  = "HARM",
                            "Specs"= list("alpha.star"=list("spec"="alpha.star","default"="0.234"),
                                          "B"=list("spec"="B","default"="NULL"))),
        "IM"         = list("name" = "Independence Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcim",
                            "alg"  = "IM",
                            "Specs"= list("mu"=list("spec"="mu","default"="rep(1, 3)"))), # vector of length Initial.Values
                # might work
#         "INCA"       = list("name" = "Interchain Adaptation",
#                             "link" = "http://www.bayesian-inference.com/mcmcinca",
#                             "alg"  = "INCA",
#                             "Specs"= list("Adaptive"=list("spec"="Adaptive","default"="500"),
#                                           "Periodicity"=list("spec"="Periodicity","default"="10"))),
        "MALA"       = list("name" = "Metropolis-Adjusted Langevin Algorithm",
                            "link" = "http://www.bayesian-inference.com/mcmcmala",
                            "alg"  = "MALA",
                            "Specs"= list("A"=list("spec"="A","default"="1e7"),
                                          "alpha.star"=list("spec"="alpha.star","default"="0.574"),
                                          "gamma"=list("spec"="gamma","default"="1"),
                                          "delta"=list("spec"="delta","default"="1"),
                                          "epsilon"=list("spec"="epsilon","default"="c(1e-6,1e-7)"))), # vector of length 2
        "MCMCMC"     = list("name" = "Metropolis-Coupled Markov Chain Monte Carlo",
                            "link" = "http://www.bayesian-inference.com/mcmcmcmcmc",
                            "alg"  = "MCMCMC",
                            "Specs"= list("lambda"=list("spec"="lambda","default"="1"),
                                          "CPUs"=list("spec"="CPUs","default"="2"),
                                          "Packages"=list("spec"="Packages","default"="NULL"),
                                          "Dyn.libs"=list("spec"="Dyn.libs","default"="NULL"))),
        "MWG"        = list("name" = "Metropolis-within-Gibbs",
                            "link" = "http://www.bayesian-inference.com/mcmcmwg",
                            "alg"  = "MWG",
                            "Specs"= list()),
        "MTM"        = list("name" = "Multiple-Try Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcmtm",
                            "alg"  = "MTM",
                            "Specs"= list("K"=list("spec"="K","default"="4"),
                                          "CPUs"=list("spec"="CPUs","default"="1"),
                                          "Packages"=list("spec"="Packages","default"="NULL"),
                                          "Dyn.libs"=list("spec"="Dyn.libs","default"="NULL"))),
        "NUTS"       = list("name" = "No-U-Turn Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcnuts",
                            "alg"  = "NUTS",
                            "Specs"= list("A"=list("spec"="A","default"="500"),
                                          "delta"=list("spec"="delta","default"="0.6"),
                                          "epsilon"=list("spec"="epsilon","default"="NULL"), # scalar
                                          "Lmax"=list("spec"="Lmax","default"="Inf"))),
        "OHSS"       = list("name" = "Oblique Hyperrectangle Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcohss",
                            "alg"  = "OHSS",
                            "Specs"= list("A"=list("spec"="A","default"="Inf"),
                                          "n"=list("spec"="n","default"="0"))),
        "pCN"        = list("name" = "Preconditioned Crank-Nicolson",
                            "link" = "http://www.bayesian-inference.com/mcmcpcn",
                            "alg"  = "pCN",
                            "Specs"= list("beta"=list("spec"="beta","default"="0.1"))),
        "RAM"        = list("name" = "Robust Adaptive Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcram",
                            "alg"  = "RAM",
                            "Specs"= list("alpha.star"=list("spec"="alpha.star","default"="0.234"),
                                          "B"=list("spec"="B","default"="NULL"),
                                          "Dist"=list("spec"="Dist","default"='"N"'),
                                          "gamma"=list("spec"="gamma","default"="0.66"),
                                          "n"=list("spec"="n","default"="0"))),
        "RDMH"       = list("name" = "Random Dive Metropolis-Hastings",
                            "link" = "http://www.bayesian-inference.com/mcmcrdmh",
                            "alg"  = "RDMH",
                            "Specs"= list()),
        "Refractive" = list("name" = "Refractive Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcrefractive",
                            "alg"  = "Refractive",
                            "Specs"= list("Adaptive"=list("spec"="Adaptive","default"="1"),
                                          "m"=list("spec"="m","default"="2"),
                                          "w"=list("spec"="w","default"="0.1"),
                                          "r"=list("spec"="r","default"="1.3"))),
        "RJ"         = list("name" = "Reversible-Jump",
                            "link" = "http://www.bayesian-inference.com/mcmcrj",
                            "alg"  = "RJ",
                            "Specs"= list("bin.n"=list("spec"="bin.n","default"="J-1"),
                                          "bin.p"=list("spec"="bin.p","default"="0.2"),
                                          "parm.p"=list("spec"="parm.p","default"="c(1, rep(1/(J-1),(J-1)), 1)"),
                                          "selectable"=list("spec"="selectable","default"="c(0, rep(1,J-1), 0)"),
                                          "selected"=list("spec"="selected","default"="c(0,rep(1,J-1),0)"))),
        "RWM"        = list("name" = "Random-Walk Metropolis",
                            "link" = "http://www.bayesian-inference.com/mcmcrwm",
                            "alg"  = "RWM",
                            "Specs"= list("B"=list("spec"="B","default"="NULL"))),
        "RSS"        = list("name" = "Reflective Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcrss",
                            "alg"  = "RSS",
                            "Specs"= list("m"=list("spec"="m","default"="5"),
                                          "w"=list("spec"="w","default"="1e-5"))),
#         "SAMWG"      = list("name" = "Sequential Adaptive Metropolis-within-Gibbs",
#                             "link" = "http://www.bayesian-inference.com/mcmcsamwg",
#                             "alg"  = "SAMWG",
#                             "Specs"= list("Dyn"=list("spec"="Dyn","default"="Dyn"),
#                                           "Periodicity"=list("spec"="Periodicity","default"="50"))),
#         "SMWG"       = list("name" = "Sequential Metropolis-within-Gibbs",
#                             "link" = "http://www.bayesian-inference.com/mcmcsmwg",
#                             "alg"  = "SMWG",
#                             "Specs"= list("Dyn"=list("spec"="Dyn","default"="Dyn"))),
        "Slice"      = list("name" = "Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcslice",
                            "alg"  = "Slice",
                            "Specs"= list("m"=list("spec"="m","default"="Inf"),
                                          "w"=list("spec"="w","default"="1"))),
#         "SGLD"       = list("name" = "Stochastic Gradient Langevin Dynamics",
#                             "link" = "http://www.bayesian-inference.com/mcmcsgld",
#                             "alg"  = "SGLD",
#                             "Specs"= list("epsilon"=list("spec"="epsilon","default"="1e-4"),
#                                           "file"=list("spec"="file","default"="X.csv"),
#                                           "Nr"=list("spec"="Nr","default"="1e4"),
#                                           "Nc"=list("spec"="Nc","default"="6"),
#                                           "size"=list("spec"="size","default"="10"))),
        "THMC"       = list("name" = "Tempered Hamiltonian Monte Carlo",
                            "link" = "http://www.bayesian-inference.com/mcmcthmc",
                            "alg"  = "THMC",
                            "Specs"= list("epsilon"=list("spec"="epsilon","default"="rep(0.05, 3)"),
                                          "L"=list("spec"="L","default"="2"),
                                          "Temperature"=list("spec"="Temperature","default"="2"))),
        # might work
#         "twalk"      = list("name" = "t-walk",
#                             "link" = "http://www.bayesian-inference.com/mcmctwalk",
#                             "alg"  = "twalk",
#                             "Specs"= list("SIV"=list("spec"="SIV","default"="NULL"),
#                                           "n1"=list("spec"="n1","default"="4"),
#                                           "at"=list("spec"="at","default"="6"),
#                                           "aw"=list("spec"="aw","default"="1.5"))),
        "UESS"       = list("name" = "Univariate Eigenvector Slice Sampler",
                            "link" = "http://www.bayesian-inference.com/mcmcuess",
                            "alg"  = "UESS",
                            "Specs"= list("A"=list("spec"="A","default"="Inf"),
                                          "B"=list("spec"="B","default"="NULL"),
                                          "m"=list("spec"="m","default"="100"),
                                          "n"=list("spec"="n","default"="0")))
#         "USAMWG"     = list("name" = "Updating Sequential Adaptive Metropolis-within-Gibbs",
#                             "link" = "http://www.bayesian-inference.com/mcmcusamwg",
#                             "alg"  = "USAMWG",
#                             "Specs"= list("Dyn"=list("spec"="Dyn","default"="Dyn"),
#                                           "Periodicity"=list("spec"="Periodicity","default"="50"),
#                                           "Fit"=list("spec"="Fit","default"="Fit"),
#                                           "Begin"=list("spec"="Begin","default"="T.m"))),
#         "USMWG"      = list("name" = "Updating Sequential Metropolis-within-Gibbs",
#                             "link" = "http://www.bayesian-inference.com/mcmcusmwg",
#                             "alg"  = "USMWG",
#                             "Specs"= list("Dyn"=list("spec"="Dyn","default"="Dyn"),
#                                           "Fit"=list("spec"="Fit","default"="Fit"),
#                                           "Begin"=list("spec"="Begin","default"="T.m")))
        )
    )